# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59dc5c2910fa67a423c2758de8907a86b43e2be7a0866bb611337831f61963cd830376eaea45730931de498176c78fa6e688fc2d1aa77ac9d76ad109320945ff

test:
  secret_key_base: eb557574a4ef33f63ec294965d8e798105f00e28e39a4390cc953dbbde0421dac0bee6102c9d5ed29e4bf91ad29511928008b434c2ad61703f6e149dc112f05c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
